### ISSUE TITLE
Memory Allocation

### ISSUE THREAD

**Issue by JoseMiguelPizarro** [platinio/PlatinioTween#1]
Hi! I really like your library, the problem I've found is that it allocated memory every time a new tween is needed. The solution i propose is to create a new TweenPool static class which can have a list for every BaseTween implementation and store them for later reuse as long as they are no longer needed. To do this BaseTween needs a new virtual method called Reset() which will be called every time a tween is being reused. So every time PlatinioTween needs a tween it  will get it from the TweenPool. What do you think?

**Comment by platinio** [comment]
Nice clean solution i already accept your changes :)

**Comment by platinio** [comment]
Solved from user
